//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_avatar : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.avatar_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Crouch
        {
            get
            {
                return SteamVR_Actions.avatar_Crouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Crawl
        {
            get
            {
                return SteamVR_Actions.avatar_Crawl;
            }
        }
        
        public virtual SteamVR_Action_Vector2 trackpadAction
        {
            get
            {
                return SteamVR_Actions.avatar_trackpadAction;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.avatar_Haptic;
            }
        }
    }
}
